### ISSUE TITLE
CallbackIntegration doesn't match it's interface

### ISSUE THREAD

**Issue by serjek** [lbergman/HxFSM#2]
/haxe_libraries/hxfsm/1.0.3/haxelib/src/hxfsm/integrations/callback/CallbackIntegration.hx:6: lines 6-15 : Field transition has different type than in hxfsm.integrations.IFSMIntegration
/haxe_libraries/hxfsm/1.0.3/haxelib/src/hxfsm/integrations/IFSMIntegration.hx:4: characters 5-75 : Interface field is defined here
/haxe_libraries/hxfsm/1.0.3/haxelib/src/hxfsm/integrations/callback/CallbackIntegration.hx:6: lines 6-15 : Different number of function arguments

**Comment by lbergman** [comment]
Thanks, been using injector integration only for some time, so seems callback integration was in a bad state. Published version 1.0.4 which should be fine, let me know if you still have issues.

**Comment by cambiata** [comment]
Hi Leo!

This seems to work fine until 1.0.5 but after that - after adding the `update:(state:StateDef) -> Void` method to the transition method, it seems - it doesn't work any more with CallbackIntegration.

No big deal for me, running with 1.0.5 seems fine for me - but I thought that I would let you know.

Best! / Jonas

**Comment by lbergman** [comment]
Thanks Jonas, will check up on the callback integration again.

**Comment by lbergman** [comment]
Made a version 2.0.2 making sure all integrations are up to date in API, so should compile now at least. Haven't done any testing on the callback integration really apart from the miniscule unit testing.
